// Generated by scripts/generate-refs-urls.ts — update with: pnpm refs:update
export default {
  greenwebfoundation: {
    home: {
      fr: 'https://www.thegreenwebfoundation.org/',
      en: 'https://www.thegreenwebfoundation.org/',
    },
    api_doc: {
      fr: 'https://developers.thegreenwebfoundation.org/api/greencheck/v3/check-single-domain/',
      en: 'https://developers.thegreenwebfoundation.org/api/greencheck/v3/check-single-domain/',
    },
  },
  ecoindex: {
    method: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#m%C3%A9thodologie-danalyse',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#m%C3%A9thodologie-danalyse',
    },
    grade: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-la-note',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-la-note',
    },
    score: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-lecoindex',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-lecoindex',
    },
    footprint: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#lempreinte-environnementale',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#lempreinte-environnementale',
    },
  },
  rweb: {
    // Legacy entries (kept for print-css.ts until Task 8)
    bp_0027: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0027',
      en: 'https://rweb.greenit.fr/en/fiches/0027',
    },
    bp_0101: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0101-ajouter-des-entetes-expires-ou-cache-control.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0101-ajouter-des-entetes-expires-ou-cache-control.html',
    },
    bp_0077: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0077-minifier-les-fichiers-css-javascript-html-et-svg.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0077-minifier-les-fichiers-css-javascript-html-et-svg.html',
    },
    bp_4006: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_4006-privilegier-http2-a-http1.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_4006-privilegier-http2-a-http1.html',
    },
    bp_0070: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0070-supprimer-tous-les-warnings-et-toutes-les-notices.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0070-supprimer-tous-les-warnings-et-toutes-les-notices.html',
    },
    bp_0095: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0095-eviter-les-redirections.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0095-eviter-les-redirections.html',
    },
    bp_0078: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0078-compresser-les-fichiers-css-javascript-html-et-svg.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0078-compresser-les-fichiers-css-javascript-html-et-svg.html',
    },
    bp_0041: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0041-ne-pas-faire-de-modification-du-dom-lorsquon-le-traverse.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0041-ne-pas-faire-de-modification-du-dom-lorsquon-le-traverse.html',
    },
    bp_0034: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0034-ne-pas-redimensionner-les-images-cote-navigateur.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0034-ne-pas-redimensionner-les-images-cote-navigateur.html',
    },
    // Entrées générées — mettre à jour avec : pnpm refs:update
    rweb_0031: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0031',
      en: 'https://rweb.greenit.fr/en/fiches/0031',
    },
    rweb_0106: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0106',
      en: 'https://rweb.greenit.fr/en/fiches/0106',
    },
    rweb_0059: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0059',
      en: 'https://rweb.greenit.fr/en/fiches/0059',
    },
    rweb_0111: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0111',
      en: 'https://rweb.greenit.fr/en/fiches/0111',
    },
    rweb_0082: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0082',
      en: 'https://rweb.greenit.fr/en/fiches/0082',
    },
    rweb_0112: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0112',
      en: 'https://rweb.greenit.fr/en/fiches/0112',
    },
    rweb_0060: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0060',
      en: 'https://rweb.greenit.fr/en/fiches/0060',
    },
    rweb_0042: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0042',
      en: 'https://rweb.greenit.fr/en/fiches/0042',
    },
    rweb_0055: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0055',
      en: 'https://rweb.greenit.fr/en/fiches/0055',
    },
    rweb_0032: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0032',
      en: 'https://rweb.greenit.fr/en/fiches/0032',
    },
    rweb_0011: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0011',
      en: 'https://rweb.greenit.fr/en/fiches/0011',
    },
    rweb_0099: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0099',
      en: 'https://rweb.greenit.fr/en/fiches/0099',
    },
    rweb_0009: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0009',
      en: 'https://rweb.greenit.fr/en/fiches/0009',
    },
    rweb_0010: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0010',
      en: 'https://rweb.greenit.fr/en/fiches/0010',
    },
    rweb_0033: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0033',
      en: 'https://rweb.greenit.fr/en/fiches/0033',
    },
    rweb_0039: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0039',
      en: 'https://rweb.greenit.fr/en/fiches/0039',
    },
    rweb_0084: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0084',
      en: 'https://rweb.greenit.fr/en/fiches/0084',
    },
    rweb_0081: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0081',
      en: 'https://rweb.greenit.fr/en/fiches/0081',
    },
  },
}
