// Generated by scripts/generate-refs-urls.ts — RWEB version: latest
export default {
  greenwebfoundation: {
    home: {
      fr: 'https://www.thegreenwebfoundation.org/',
      en: 'https://www.thegreenwebfoundation.org/',
    },
    api_doc: {
      fr: 'https://developers.thegreenwebfoundation.org/api/greencheck/v3/check-single-domain/',
      en: 'https://developers.thegreenwebfoundation.org/api/greencheck/v3/check-single-domain/',
    },
  },
  ecoindex: {
    method: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#m%C3%A9thodologie-danalyse',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#m%C3%A9thodologie-danalyse',
    },
    grade: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-la-note',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-la-note',
    },
    score: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-lecoindex',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-lecoindex',
    },
    footprint: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#lempreinte-environnementale',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#lempreinte-environnementale',
    },
  },
  rweb: {
    bp_0027: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0027-mettre-en-place-une-architecture-elastique',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0027-set-up-an-elastic-architecture',
    },
    bp_0034: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0034-utiliser-le-rechargement-partiel-d-une-zone-de-contenu',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0034-use-partial-content-reloading',
    },
    bp_0041: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0041-ecrire-des-selecteurs-css-efficaces',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0041-write-efficient-css-selectors',
    },
    bp_0070: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0070-utiliser-un-cdn',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0070-use-a-cdn',
    },
    bp_0077: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0077-minifier-les-fichiers-css-javascript-html-et-svg',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0077-minifying-text-files-css-js-html-and-svg',
    },
    bp_0078: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0078-combiner-les-fichiers-css-et-javascript',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0078-combining-css-and-javascript-files',
    },
    bp_0095: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0095-privilegier-un-fournisseur-d-electricite-ecoresponsable',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0095-choose-an-eco-friendly-electricity-provider',
    },
    bp_0101: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0101-n-utiliser-que-des-fichiers-double-opt-in',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0101-only-use-e-mails-validated-by-double-consent',
    },
    bp_4006: {
      fr: 'https://rweb.greenit.fr/fr/fiches/4006',
      en: 'https://rweb.greenit.fr/en/fiches/4006',
    },
    rweb_0009: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0009-eviter-les-animations-javascript-css',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0009-avoid-javascriptcss-animations',
    },
    rweb_0010: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0010-limiter-le-recours-aux-carrousels',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0010-limiting-the-use-of-carousels',
    },
    rweb_0011: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0011-avoir-un-titre-de-page-et-une-metadescription-pertinents-avec-le-contenu-de-la-page',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0011-relevant-page-titles-and-metadescriptions',
    },
    rweb_0031: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0031-fournir-une-css-print',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0031-provide-a-css-print',
    },
    rweb_0032: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0032-favoriser-les-polices-standards',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0032-prefer-standard-fonts',
    },
    rweb_0033: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0033-ne-pas-afficher-les-documents-a-l-interieur-des-pages',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0033-do-not-display-documents-within-pages',
    },
    rweb_0039: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0039-utiliser-les-compartiments-css',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0039-use-css-containment',
    },
    rweb_0042: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0042-externaliser-les-css-et-javascript',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0042-externalize-css-and-javascript',
    },
    rweb_0055: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0055-limiter-le-recours-aux-canvas',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0055-limit-canvas-use',
    },
    rweb_0059: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0059-remplacer-les-boutons-officiels-de-partage-des-reseaux-sociaux',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0059-replace-the-official-social-network-sharing-buttons',
    },
    rweb_0060: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0060-economiser-de-la-bande-passante-grace-a-un-serviceworker',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0060-save-bandwidth-with-service-workers',
    },
    rweb_0081: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0081-heberger-les-ressources-cssjs-sur-un-domaine-sans-cookie',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0081-host-static-resources-on-a-cookie-free-domain',
    },
    rweb_0082: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0082-limiter-le-nombre-de-domaines-servant-les-ressources',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0082-limit-the-number-of-domains-serving-resources',
    },
    rweb_0084: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0084-favoriser-hsts-preload-list-aux-redirections-301',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0084-favor-hsts-preload-list-over-301-redirects',
    },
    rweb_0099: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0099-limiter-l-utilisation-des-gifs-animes',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0099-limit-the-use-of-animated-gif',
    },
    rweb_0106: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0106-eviter-la-lecture-et-le-chargement-automatique-des-videos-et-des-sons',
      en: 'https://rweb.greenit.fr/es/fiches/RWEB_0106-evitar-la-reproduccion-y-carga-automatica-de-videos-y-sonidos',
    },
    rweb_0111: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0111-limiter-les-outils-d-analytics-et-les-donnees-collectees',
      en: 'https://rweb.greenit.fr/es/fiches/RWEB_0111-limitar-las-herramientas-de-analisis-y-los-datos-recopilados',
    },
    rweb_0112: {
      fr: 'https://rweb.greenit.fr/fr/fiches/RWEB_0112-eviter-les-redirections',
      en: 'https://rweb.greenit.fr/en/fiches/RWEB_0112-avoir-redirections',
    },
  },
}
