#!/usr/bin/env tsx
/**
 * Génère libs/ecoindex-lh-plugin-ts/src/audits/bp/refs-urls.ts
 * en interrogeant l'API RWEB pour chaque ID × locale.
 *
 * Usage:
 *   pnpm refs:update                    # version latest
 *   pnpm refs:update:version -- 2.0.0   # version spécifique
 */

import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const RWEB_IDS = [
  '0009', '0010', '0011', '0031', '0032', '0033',
  '0039', '0042', '0055', '0059', '0060', '0081',
  '0082', '0084', '0099', '0106', '0111', '0112',
]
const LOCALES: Array<'fr' | 'en'> = ['fr', 'en']
const BASE_URL = 'https://rweb.greenit.fr'

function parseVersion(args: string[]): string {
  const idx = args.indexOf('--version')
  if (idx !== -1 && args[idx + 1]) return args[idx + 1]
  return 'latest'
}

async function fetchFicheUrl(id: string, lang: string, version: string): Promise<string> {
  const fallback = `${BASE_URL}/${lang}/fiches/${id}`
  try {
    const apiUrl = `${BASE_URL}/api/fiches/${id}?lang=${lang}${version !== 'latest' ? `&version=${version}` : ''}`
    const res = await fetch(apiUrl, { signal: AbortSignal.timeout(5000) })
    if (res.ok) {
      const data = await res.json() as Record<string, unknown>
      if (typeof data?.url === 'string') return data.url
      if (typeof data?.slug === 'string') return `${BASE_URL}/${lang}/fiches/${data.slug}`
    }
  } catch {
    // fall through to default URL
  }
  return fallback
}

async function main() {
  const version = parseVersion(process.argv.slice(2))
  console.log(`Generating refs-urls.ts — RWEB version: ${version}`)

  const rweb: Record<string, Record<string, string>> = {}

  for (const id of RWEB_IDS) {
    const key = `rweb_${id}`
    rweb[key] = {}
    for (const lang of LOCALES) {
      process.stdout.write(`  Fetching ${id} [${lang}]...`)
      rweb[key][lang] = await fetchFicheUrl(id, lang, version)
      console.log(' ✓')
    }
  }

  const rwebBlock = Object.entries(rweb)
    .map(([key, urls]) => {
      const lines = Object.entries(urls)
        .map(([lang, url]) => `      ${lang}: '${url}',`)
        .join('\n')
      return `    ${key}: {\n${lines}\n    },`
    })
    .join('\n')

  const output = `// Generated by scripts/generate-refs-urls.ts — RWEB version: ${version}
export default {
  greenwebfoundation: {
    home: {
      fr: 'https://www.thegreenwebfoundation.org/',
      en: 'https://www.thegreenwebfoundation.org/',
    },
    api_doc: {
      fr: 'https://developers.thegreenwebfoundation.org/api/greencheck/v3/check-single-domain/',
      en: 'https://developers.thegreenwebfoundation.org/api/greencheck/v3/check-single-domain/',
    },
  },
  ecoindex: {
    method: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#m%C3%A9thodologie-danalyse',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#m%C3%A9thodologie-danalyse',
    },
    grade: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-la-note',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-la-note',
    },
    score: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-lecoindex',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#le-calcul-de-lecoindex',
    },
    footprint: {
      fr: 'https://www.ecoindex.fr/comment-ca-marche/#lempreinte-environnementale',
      en: 'https://www.ecoindex.fr/comment-ca-marche/#lempreinte-environnementale',
    },
  },
  rweb: {
    // Legacy entries (kept for backward compatibility with older audits)
    bp_0027: {
      fr: 'https://rweb.greenit.fr/fr/fiches/0027',
      en: 'https://rweb.greenit.fr/en/fiches/0027',
    },
    bp_0101: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0101-ajouter-des-entetes-expires-ou-cache-control.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0101-ajouter-des-entetes-expires-ou-cache-control.html',
    },
    bp_0077: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0077-minifier-les-fichiers-css-javascript-html-et-svg.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0077-minifier-les-fichiers-css-javascript-html-et-svg.html',
    },
    bp_4006: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_4006-privilegier-http2-a-http1.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_4006-privilegier-http2-a-http1.html',
    },
    bp_0070: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0070-supprimer-tous-les-warnings-et-toutes-les-notices.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0070-supprimer-tous-les-warnings-et-toutes-les-notices.html',
    },
    bp_0095: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0095-eviter-les-redirections.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0095-eviter-les-redirections.html',
    },
    bp_0078: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0078-compresser-les-fichiers-css-javascript-html-et-svg.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0078-compresser-les-fichiers-css-javascript-html-et-svg.html',
    },
    bp_0041: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0041-ne-pas-faire-de-modification-du-dom-lorsquon-le-traverse.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0041-ne-pas-faire-de-modification-du-dom-lorsquon-le-traverse.html',
    },
    bp_0034: {
      fr: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0034-ne-pas-redimensionner-les-images-cote-navigateur.html',
      en: 'https://ref.greenit.fr/rweb/fr/fiches/rweb_0034-ne-pas-redimensionner-les-images-cote-navigateur.html',
    },
    // Entrées générées — mettre à jour avec : pnpm refs:update
${rwebBlock}
  },
}
`

  const outPath = resolve(
    __dirname,
    '../libs/ecoindex-lh-plugin-ts/src/audits/bp/refs-urls.ts',
  )
  writeFileSync(outPath, output, 'utf-8')
  console.log(`\n✓ Written: ${outPath}`)
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
