version: '3.8'

services:
  lhserver:
    platform: linux/amd64
    # image: patrickhulce/lhci-server
    build:
      context: ./server
      dockerfile: Dockerfile.lhci-server
    command: sleep infinity
    # ports:
    #   - '9001:9001'
    volumes:
      # - lhci-data-silicon:/data
      - ./data:/data
